"""add book category_id

Revision ID: ab59fd236f49
Revises: 916cad8ec3db
Create Date: 2026-08-17 21:45:42.175149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab59fd236f49'
down_revision: Union[str, Sequence[str], None] = '916cad8ec3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
